apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-service-deployment
spec:
  selector:
    matchLabels:
      app: employee-service
  replicas: 2
  template:
    metadata:
      labels:
        app: employee-service
    spec:
      containers:
        - name: employee-service
          image: anurodhsingh/employee-service:version-1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8050